# IMPORTANDO LIBRERÍAS

In [ ]:
import numpy as np # np es alias de numpy
import pandas as pd # pd es alias de pandas
import sys # este paquete maneja funciones de sistema

In [ ]:
print("Hi World!")

Hi World!


In [ ]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
unos = np.ones(10)
unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
ceros = np.zeros(10)
ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
lista2 = ["Benja", 10, 7.6, True]
lista2

['Benja', 10, 7.6, True]

In [ ]:
arreglo2 = np.array(lista2)
arreglo2

array(['Benja', '10', '7.6', 'True'], dtype='<U32')

In [ ]:
memoria_lista = sys.getsizeof(lista)
memoria_lista

136

In [ ]:
arreglo.dtype

dtype('int64')

In [ ]:
promedio = np.mean(lista)
promedio

np.float64(5.5)

In [ ]:
new_arreglo = arreglo.astype(np.float32)
new_arreglo

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [ ]:
np.random.rand(5)

array([0.41814888, 0.32526759, 0.3585398 , 0.99600311, 0.21233923,
       0.38797241])

In [ ]:
np.random.randint(1,100,100)

array([23, 56, 65, 38, 29, 87, 49, 11, 60, 74, 70, 27, 99, 44, 52, 37,  8,
       98, 65, 54, 89, 27, 52, 65, 79, 91, 90, 83, 88, 36, 15, 31, 56, 47,
       30, 17, 23, 46, 29, 81, 75,  5, 48, 82, 98, 21, 85, 54, 55, 69, 88,
       38, 51, 86, 10, 40, 80, 44, 58, 61, 53, 59,  7, 10, 43, 69, 74, 88,
       58, 85, 58, 93, 91, 22, 39, 22, 73, 39, 11, 73, 18, 64,  4, 21, 22,
       42, 28, 50, 22, 27, 48, 22, 22, 85, 46, 93, 10, 93, 58, 97])